name: Develop PR - build test

on:
  pull_request:
    branches:
      - develop

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ./

      -
        name: Install just
        uses: extractions/setup-just@v1

      -
        name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      # Saves us from having to redownload all modules
      - name: Go Mod cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      -
        name: Test
        run: |
          just test

      -
        name: Build
        run: |
          just build-local

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ./

      -
        name: Install just
        uses: extractions/setup-just@v1

      -
        name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18.3.0'

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('./ui/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      -
        name: Build
        working-directory: ./ui
        run: |
          just build-local
